language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="2bf0aa8d-a3cd-483c-94cb-a16d5534a3d1"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -emelyanov.am@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
